### ISSUE TITLE
CA connections "stalled" after sleeping

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/epics-base#190]
I occasionally run IOCs on a raspberry pi board over wifi at my apartment.  When I do, I occasionally notice long reconnect times after waking up my laptop in the morning.  Last night I had left phoebus and a camonitor instance running.  Recalling @anjohnson complaining of anomalous long reconnect times, after waiting for 1 minute I started wireshark recording instead of impatiently reloading/restarting as I otherwise would (I don't do mornings well).

I saw no searches being sent, but did see beacons from the IOCs (two, both on the pi board).

`netstat` on the laptop showed that both clients having active TCP connections, with non-zero `Send-Q`.  `netstat` on the pi board showed no active connections (as expected).

```
$ netstat -tpn|grep 192.168.1.79
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0     32 192.168.1.68:33486      192.168.1.79:5064       ESTABLISHED 10604/./bin/linux-x 
tcp6       0     16 192.168.1.68:33504      192.168.1.79:5064       ESTABLISHED 3017/java           
tcp6       0     16 192.168.1.68:53762      192.168.1.79:37457      ESTABLISHED 3017/java
```

I did see a single ECHO request sent on two of the three connections (33486 and 33504), but no reply.  (the IOCs had timed out long before).

After about 5 minutes I begin seeing TCP Retransmission requests on all three connections, repeating at ~30 second intervals.

(I'm surprised that none of this provoked a RST from the Linux IP stack the pi board)

Eventually, after ~15 minutes, something seemed to provoke both clients into reconnecting.

**Comment by mdavidsaver** [comment]
The output of camonitor while this was happening.  The laptop woke about at ~08:14.  So the first "Virtual circuit unresponsive" happened on schedule, but doesn't seem to have had the desired result.

```
$ ./bin/linux-x86_64/camonitor LIGHT:Gain-SP{,.RVAL}
LIGHT:Gain-SP                  2021-07-26 21:09:27.909038 g64.0x  
LIGHT:Gain-SP.RVAL             2021-07-26 21:09:27.909038 3  
LIGHT:Gain-SP                  2021-07-27 08:14:33.020745 *** disconnected
LIGHT:Gain-SP.RVAL             2021-07-27 08:14:33.020775 *** disconnected
CA.Client.Exception...............................................
    Warning: "Virtual circuit unresponsive"
    Context: "raspberrypi:5064"
    Source File: ../tcpiiu.cpp line 926
    Current Time: Tue Jul 27 2021 08:14:33.020724952
..................................................................
... long silence ...
Unexpected problem with CA circuit to server "raspberrypi:5064" was "Network is unreachable" - disconnecting
CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "raspberrypi:5064"
    Source File: ../cac.cpp line 1237
    Current Time: Tue Jul 27 2021 08:30:14.790727399
..................................................................
LIGHT:Gain-SP                  2021-07-26 21:09:27.909038 g64.0x  
LIGHT:Gain-SP.RVAL             2021-07-26 21:09:27.909038 3
```

**Comment by mdavidsaver** [comment]
Odd that both libca and CAJ seem to behave similarly.  I would otherwise be inclined to suspect the epicsTimer code.

The only other possibility which comes to mind is a blocking `send()`, which I know that both implementations do.  Still, while `netstat` shows a non-empty send buffer, it is nowhere near full.

**Comment by tboegi** [comment]
@mdavidsaver : Some questions:
That is on the client-side: "...both libca and CAJ seem to behave similarly", right ?

"Still, while netstat shows a non-empty send buffer, it is nowhere near full."
Is this the netstat on the server ?
How full is it ? Or, do we have an idea what is inside ?
I have the slight suspicion that the Linux kernel on the server side does not send
out the "packets" as we expect it.

We have seen similar scenarios where e.g. a polling request from the IOC to a
device via asyn is buffered, and filling the send buffer seems to confuse the TCP timers,
which should give us a "connection timeout" after 2 minutes (?) on the server side.
It could be interesting to see what the client and server "put into the socket" by calling
send(), what we see on the wire/wireless and what the other side receives.

**Comment by mdavidsaver** [comment]
This issue seemed to go away after an OS re-install (for an unrelated reason).  Perhaps this networking weirdness was the result of some misconfiguration on my part?
