### ISSUE TITLE
Posix implementation of epicsEvent is unsuitable for RTEMS-posix targets 

### ISSUE THREAD

**Issue by anjohnson** [epics-base/epics-base#202]
The code in libCom/osi/os/posix/osdEvent.c was written for workstation OSs that don't support true ISRs. The `struct epicsEventOSD` in that file which implements the epicsEvent object contains both a `pthread_mutex_t` and a `pthread_cond_t`. Unfortunately neither of these can be used in ISR context on an RTEMS-posix target. The `epicsEventTrigger()` routine must be callable from ISR context when the target supports them.

Discovered by @hjunkes and @mdavidsaver.

**Comment by hjunkes** [comment]
For a first try I copied osdEvent.c from RTEMS-kernel to RTEMS-posix.
I commented out the show routine first. This uses old internal calls.
And replaced extern double rtemsTicksPerSecond_double by rtems_clock_get_ticks_per_second(). 
The test system has been running for 1.5 hours. Longer than before ;-) I have to observe this further and then adjust osdEvent.c properly.

**Comment by anjohnson** [comment]
Can the `rtems_semaphore_*()` routines be used on SMP systems?

**Comment by hjunkes** [comment]
My first suggestion for osdEvent.c for libcom/src/osi/os/RTEMS-posix
It uses self contained objects (rtems_binary_semaphore): 
https://docs.rtems.org/branches/master/c-user/self_contained_objects.html#binary-semaphore

[osdEvent.c.txt](https://github.com/epics-base/epics-base/files/7259201/osdEvent.c.txt)

**Comment by anjohnson** [comment]
Seems like a reasonable start. Please change the Author at the top and remove the Saskatchewan copyright (you can add an FHI or one of your own if you need/wish to).

Note that `&(pSem->rbs)` is equivalent to `&pSem->rbs` since `->` [takes precedence](https://en.cppreference.com/w/c/language/operator_precedence) over `&` — I find the latter easier to read at a glance since I don't have to match up the parentheses.

Please look at the VxWorks implementation of `epicsEventWaitWithTimeout()` which shows the issues that can arise with the conversion of seconds into ticks. The `timeOut` parameter may be negative or zero (these both mean to poll the event and return immediately without waiting, so you could call `rtems_binary_semaphore_try_wait()` in that case), or can overflow when converted to ticks. An overflow is allowed to mean wait forever (as long as its's some reasonably large time period), and it looks like `rtems_binary_semaphore_wait_timed_ticks()` accepts 0 ticks to mean that or you could just call `rtems_binary_semaphore_wait()` in that case.

Thanks!

**Comment by hjunkes** [comment]
ok, I have done that. I will put the file osdEvent.c here again. Unfortunately I don't know who is currently maintaining the RTEMS-path in Epics. Brandan
[osdEvent.c.txt](https://github.com/epics-base/epics-base/files/7331223/osdEvent.c.txt)

**Comment by anjohnson** [comment]
Now that the RTEMS-5 port has been merged we can all make changes; no one person is in charge of it. See my PR #206 for future discussion of this code.

I made a few cosmetic changes to your original and added an osdEvent.h header which should be present as well (sorry I forgot to mark you as the author in Git when I committed them).

Thanks!
