### ISSUE TITLE
SingletonUntyped::pInstance warning

### ISSUE THREAD

**Issue by tboegi** [epics-base/epics-base#207]
Folks,
compiling EPICS under Mingw gives a bunch of these warnings
(Any hints how to fix it ? I can prepare a PR)

g++             -D_MINGW -D__USE_MINGW_ANSI_STDIO   -DBUILDING_libCa_API   -O3   -Wall      -m64    -DEPICS_BUILD_DLL -DEPICS_CALL_DLL   -I. -I../O.Common -I. -I. -I.. -I../test -I../../../../../include/compiler/gcc -I../../../../../include/os/WIN32 -I../../../../../include         -o netSubscription.obj -c ../netSubscription.cpp
In file included from ../localHostName.h:27,
                 from ../cac.h:32,
                 from ../netSubscription.cpp:30:
../../../../../include/epicsSingleton.h:164:15: warning: 'void* SingletonUntyped::pInstance() const' redeclared without dllimport attribute after being referenced with dll linkage
  164 | inline void * SingletonUntyped :: pInstance () const
      |               ^~~~~~~~~~~~~~~~

**Comment by ralphlange** [comment]
Windows decorations issue.
In many cases this happens when a unit (cpp file) uses a library function without properly including its header file (relying on some other header to include it instead).

**Comment by FreddieAkeroyd** [comment]
The `SingletonUntyped` class is defined as `LIBCOM_API ` in `epicsSingleton.h`, maybe MinGW wants  `LIBCOM_API`  added to the method or data item if it is inlined? I don't see the warning in my visual studio with a normal build, I will try upping the warning level and see if it will say something like this there too. If the file was included in multiple places with an incorrect/mismatch `LIBCOM_API` definition then that could also create similar issue, which is what Ralph is referring to, i though i migth have seen that in visual studio too but maybe that is only in debug mode. Anyway i'll try a VS recompile and see what i see.

**Comment by FreddieAkeroyd** [comment]
Hi, I compiled with visual studio and `-Wall` in debug and non-debug mode and I don't get a similar looking warning, so it looks like a MinGW only issue.  If you remove the `inline` from line 164 in epicsSingleton.h does that help get rid of the warning? If so maybe you need to add LIBCOM_API to `_pInstance` or something like that, as it is private rather than public it may not inherit `LIBCOM_API` from the class

**Comment by tboegi** [comment]
Thanks for testing - I will try this tomorrow.

**Comment by mdavidsaver** [comment]
> If you remove the `inline` from line 164 in epicsSingleton.h

I think it would also be necessary to add an `inline` on line 32.  Or just move this, and the other, trivial definitions inline...

**Comment by tboegi** [comment]
Thanks for the comments.

https://github.com/epics-base/epics-base/pull/208

**Comment by tboegi** [comment]
Interesting approach from the Core developpers.
A simple patch, which passes the appveyor tests:
https://ci.appveyor.com/project/epics-base-7/epics-base/builds/41143108
Is replaced by a commit directly to the 7.0 branch:
https://github.com/epics-base/epics-base/commit/2b3c6f2e262a7dfc506cce66547ad2dc74d8a80b
And failing the tests:
https://ci.appveyor.com/project/mdavidsaver/epics-base/builds/41187871

I think I am done here

**Comment by mdavidsaver** [comment]
> A simple patch, ...

Both [Andrew](https://github.com/epics-base/epics-base/pull/208#issuecomment-943423933) and I gave suggestions for a more complete fix.  imo. your simple patch only addresses the one template method which happens not to be inline'd on some builds.  The same could happen with any of the others.

> And failing the tests:

Which is unrelated https://github.com/epics-base/epics-base/discussions/162#discussioncomment-1460745

> I think I am done here

Over a one line patch?  I'm sorry to hear this.
