### ISSUE TITLE
Client using ca_enable_preemptive_callback gets no monitor updates

### ISSUE THREAD

**Issue by hinxx** [epics-base/epics-base#209]
I have a CA client using `ca_enable_preemptive_callback`. The `ca_create_subscription` is called and events received. If I call `ca_clear_subscription` and  `ca_create_subscription` again monitor events do not arrive anymore.

I realized that calling `ca_poll` after second `ca_create_subscription` solves the issue for me.

Bug or feature? 

In my client code I do not have any calls to to `ca_poll`, `ca_pend_io` or `ca_pend_event` anywhere because [magic](https://github.com/epics-base/epics-base/blob/a662cae2398f0bfa1c04a9ba5e7e45da582374d6/modules/ca/src/client/CAref.html#L2631).

code: 
[caMonitor.txt](https://github.com/epics-base/epics-base/files/7412384/caMonitor.txt)

EPICS base R7.0.6.1.

**Comment by anjohnson** [comment]
A feature. The [documentation](https://epics.anl.gov/base/R7-0/6-docs/CAref.html#ca_add_event) for `ca_create_subscription()` says:

> All subscription requests such as the above are accumulated (buffered) and not forwarded to the IOC until one of `ca_flush_io()`, `ca_pend_io()`, `ca_pend_event()`, or `ca_sg_block()` are called. This allows several requests to be efficiently sent over the network in one message.

`ca_poll()` is a synonym for `ca_pend_event(0.0)` and also flushes the send buffer, although it probably should have been explicitly mentioned above too.

Thus replacing your call to `ca_poll()` with `ca_flush_io()` is the recommended solution.
