### ISSUE TITLE
/src/tools/makeRPath.py shebang does not specify python version

### ISSUE THREAD

**Issue by daykin** [epics-base/epics-base#227]
The 'makeRPath' python script in /src/tools uses a `#!/usr/bin/env python` shebang. This results in using the default python2 on Debian systems, which is deprecated with the release of Debian 11 (bullseye). Does this need to be run on python 2 (in which case the shebang should be changed to `#!/usr/bin/env python2` or can python3 be specified?

**Comment by mdavidsaver** [comment]
The `#!` line is practically a matter of decoration (or hints to an IDE).  Execution is done after expanding the make variable `$(PYTHON)`, which defaults to `python` but may be overwritten in eg. `configure/CONFIG_SITE.local`.

https://github.com/epics-base/epics-base/blob/91941af992f6c32ef4f4ef55a2952f581aeee36a/configure/CONFIG_BASE#L49

The `makeRPath.py` script, like all python scripts include in Base, should run work with python 2.7 or >= 3.4.

**Comment by mdavidsaver** [comment]
Also, I suggest pointing `/usr/bin/python` to `python3`.

```sh
apt-get install python-is-python3
```

**Comment by daykin** [comment]
OK, thank you for the advice. I guess I should add a bit more context: I am not running into any issues with it directly, however, I am creating a debian package for Base 7.0.6 and Lintian throws an error about it. Would you rather I patch this only for our local version, or would you accept a PR to change it to a specific version?

**Comment by mdavidsaver** [comment]
Well... personally I'm not enthused about replacing `/usr/bin/python`.  It seems like unnecessary churn to me.  Were I in your place, I'd just patch it out, or add a lintian override, and revisit the question after the next debian stable release.

**Comment by daykin** [comment]
OK, will do. thanks.
