### ISSUE TITLE
Sequence record SHIFT (Mask) documentation incorrect

### ISSUE THREAD

**Issue by wtup** [epics-base/epics-base#236]
There's a discrepancy between SHIFT description from the documentation and code implementation.

Code:
https://github.com/epics-base/epics-base/blob/7.0/modules/database/src/std/rec/seqRecord.c#L171

Documentation:
https://github.com/epics-base/epics-base/blob/7.0/modules/database/src/std/rec/seqRecord.dbd.pod#L116

**Comment by anjohnson** [comment]
Fixed in #237 now merged.
