### ISSUE TITLE
Undefined timestamp on first camonitor update of NORD field

### ISSUE THREAD

**Issue by bhill-slac** [epics-base/epics-base#258]
SLAC is seeing a problem when client apps are monitoring the NORD field of image waveforms.
If the client app is running and has a CA monitor pending, when the IOC boots
the monitor first reports UDF as the waveform has not yet processed.
Once it does, the first update doesn't get a timestamp.
A fresh caget or camonitor does see the timestamp.
% camonitor ioc:fillingwaveform.NORD
ioc:fillingwaveform.NORD       <undefined> 0 UDF INVALID
ioc:fillingwaveform.NORD       <undefined> 3 UDF INVALID
ioc:fillingwaveform.NORD       <undefined> 3 UDF INVALID
ioc:fillingwaveform.NORD       2022-05-12 14:18:00.721198 5  
ioc:fillingwaveform.NORD       2022-05-12 14:18:00.721198 5

**Comment by bhill-slac** [comment]
[test.db.txt](https://github.com/epics-base/epics-base/files/8682707/test.db.txt)

**Comment by bhill-slac** [comment]
To trigger the bug, I start the camonitor then run:
$EPICS_BASE/bin/$EPICS_HOST_ARCH/softIoc -d test.db

Then
dbpf ioc:fillingwaveform.PROC 1

**Comment by anjohnson** [comment]
Investigation: The waveformRecord's `readValue()` calls
```
  db_post_events(prec, &prec->nord, DBE_VALUE | DBE_LOG);
```
after NORD gets updated, that needs to be moved into process() after the timestamp is set.

**Comment by bhill-slac** [comment]
Thanks, I'll give it a try!

**Comment by bhill-slac** [comment]
Looks like that works for a fix.   I'll work on adding a test case and push that first.

**Comment by anjohnson** [comment]
Core Group 9/29: Fixed with #263
