### ISSUE TITLE
size of array error 

### ISSUE THREAD

**Issue by banerian** [epics-base/epics-base#3]
referenced file:
src/libCom/test/epicsExceptionTest.cpp
epics (stable) version 3.15.4
compiler: gcc, cpp, g++ version 6.1.1

/epicsExceptionTest.cpp: In function ‘void epicsExceptionTestPrivate()’:
../epicsExceptionTest.cpp:61:49: error: size of array is too large
         char \* p = new char [unsuccessfulNewSize];
                                                 ^
../epicsExceptionTest.cpp:74:38: error: size of array is too large
             char [unsuccessfulNewSize];
                                      ^

**Comment by mdavidsaver** [comment]
One workaround suggested by Bob Soliday is to remove the const from the definition of 'unsuccessfulNewSize', which will prevent GCC from making this check.

http://www.aps.anl.gov/epics/tech-talk/2016/msg01118.php

Please direct further comments to

https://bugs.launchpad.net/epics-base/+bug/1611876
