### ISSUE TITLE
VXWORKS version check macro hole

### ISSUE THREAD

**Issue by till-s** [epics-base/epics-base#307]
I just saw this and before I forget (`modules/libcom/src/osi/os/vxWorks/osdFindSymbol.c`, `./modules/libcom/src/osi/os/vxWorks/epicsDynLink.c`)

      #if _WRS_VXWORKS_MAJOR < 6 || _WRS_VXWORKS_MINOR < 9

will trigger once 7.0 is out; should probably be  `MAJOR < 6 || (MAJOR==6 && MINOR < 9)`

**Comment by anjohnson** [comment]
True, but only ANL and PSI are really using VxWorks now and AFAIK neither are planning to upgrade to VxWorks 7, which has been out for years but doesn't have BSP support for the VME boards that we have historically built our IOCs on. If a site wants to run EPICS IOCs on VxWorks 7 I believe they will have some porting work to do for a few other APIs, but we'd be happy to work with anyone who steps up to develop and maintain such a port.

**Comment by mdavidsaver** [comment]
Closing as "not planned" since I don't think anyone is considering undertaking a vxworks 7 port.
