### ISSUE TITLE
dbLoadRecords() should warn or error if an alias is specified with a field part.

### ISSUE THREAD

**Issue by anjohnson** [epics-base/epics-base#312]
See https://epics.anl.gov/tech-talk/2022/msg01938.php

Note that this issue is _not_ about supporting aliases that can point to fields, that would be a much larger and non-trivial change.

**Comment by EmilioPeJu** [comment]
I would like to do this one

**Comment by EmilioPeJu** [comment]
Fixed by PR 336

**Comment by anjohnson** [comment]
This was fixed by #336
