### ISSUE TITLE
Add tests for PR #310

### ISSUE THREAD

**Issue by anjohnson** [epics-base/epics-base#314]
PR #310 fixed an issue when fprintf() fails, it would be nice to have tests for that if it's possible to do in a cross-platform way.

**Comment by AlexanderWells-diamond** [comment]
I'm looking at this one

**Comment by AlexanderWells-diamond** [comment]
Test has been merged into PR #310 so this can be closed at the same time that is.

**Comment by anjohnson** [comment]
All changes were merged, see comments to #310
