### ISSUE TITLE
[7.0.7][ppc64el, riscv64, s390x] Architecture 'XXX' not recognized

### ISSUE THREAD

**Issue by picca** [epics-base/epics-base#412]
where XXX is

- powerpc64le-linux-gnu-thread-multi
- riscv64-linux-gnu-thread-multi
- s390x-linux-gnu-thread-multi
I do not know If you want to support these architecture, but the info is here :).

Cheers

**Comment by mdavidsaver** [comment]
epics-base does not current support these targets.  Contributions welcomed.  We support PPC32, so PPC64 at least would likely not require a huge effort.  Some familiarity with our (strange) makefiles will be necessary though.

The error you quote is coming from `EpicsHostArch.pl`.  As a note, this is only the first place where target/architecture is referenced.  Look under `configure/os/`.

https://github.com/epics-base/epics-base/blob/524f81b8bd147bb714c9ea7b7462b8912a134246/src/tools/EpicsHostArch.pl#L35-L45
