### ISSUE TITLE
struct link change in commit e88a186

### ISSUE THREAD

**Issue by dirk-zimoch** [epics-base/epics-base#473]
The commit message  of commit e88a186 is "make link::flags bit field unsigned" but the change `short` to `unsigned` also makes the field longer and thus changes alignment and padding in the structure. On 32 bit architectures, this increases the size of `struct link` by 4 bytes:

Before, the structure layout was on 32 bit architectures:
pointer (4), short (2), short (2), pointer (4),... (12 bytes so far)
and on 64 bit architectures:
pointer (8), short (2), short (2), padding (4), pointer(8),... (24 bytes)

And is now on 32 bit systems
pointer (4), short (2), padding(2), unsigned (4), pointer (4),... (16 bytes)
and on 64 bit systems:
pointer (8), short (2), padding(2), unsigned (4), pointer (8),... (24 bytes)

Is this intentional / necessary? According to the commit message, the change should have been `short` to `unsigned short`

**Comment by mdavidsaver** [comment]
> Is this intentional / necessary? According to the commit message, the change should have been `short` to `unsigned short`

No, not intentional.  My mistake.  Fixed with cb1571783b4793cb9c545e5736659ee5ed7d03bb

I am glad I waited until just after the 7.0.8 release to push that batch "cleanup" changes...
