### ISSUE TITLE
Documentation of the aSub record type

### ISSUE THREAD

**Issue by anjohnson** [epics-base/epics-base#479]
There are 21 sets of input and output variable and link fields in an aSub record, `A` through `U`. The documentation says 20 though and I've always thought that was the actual number. It's only taken me 16 years (and a colleague who will be using 20 inputs) to realize that was wrong...

**Comment by chrisalguerrero** [comment]
I will make the change to the aSubRecord.dbd.pod file to reflect the correct number of IO fields

**Comment by anjohnson** [comment]
Closed by #504
