### ISSUE TITLE
CA client does not use localhost interface by default

### ISSUE THREAD

**Issue by hinxx** [epics-base/epics-base#554]
When running a soft IOC on Linux with the `export EPICS_CAS_INTF_ADDR_LIST=localhost` set, I can not reach its PVs from localhost with the CA client without explicitly setting `export EPICS_CA_ADDR_LIST=localhost`.

It seems that only in case there a no network interfaces on the host (no network cards?) would the CA code attempt to use localhost.

https://github.com/epics-base/epics-base/blob/152d306ad87dfd6fc8992330d6f29a86fb81533b/modules/ca/src/client/iocinf.cpp#L211-L218

Is there a reason why this is the case and the localhost is treated this way?

**Comment by ralphlange** [comment]
If name resolution always sent to localhost on regular one-NIC hosts, replies from local IOCs would get back to the client through two interfaces (localhost and the NIC), causing error messages and arbitrary connections through either one.
