### ISSUE TITLE
compress record FIFI/LIFO not working

### ISSUE THREAD

**Issue by dschick** [epics-base/epics-base#9]
Starting from epics-base 3.16, the insert of new values into the compress record does not work properly.
The values are not inserted at the beginning or end of the ring buffer but somewhere in its center.

See detailed description:
https://epics.anl.gov/tech-talk/2018/msg00017.php

**Comment by ralphlange** [comment]
Dear @dschick,
The EPICS Base code is hosted at LaunchPad and uses the LaunchPad issue tracker, where this matter is now handled at https://bugs.launchpad.net/epics-base/+bug/1743795
Closing the issue.
